### ISSUE TITLE
How to seek gzipped tar files?

### ISSUE THREAD

**Issue by remorses** [jeffallen/seekinghttp#3]
I want to extract a list of files from a Docker layer url without downloading the full layer, docker registries store layers as .tar.gz files, this means that I can’t directly use the Range header to seek into the tar file because there is the gzip compression on top, making tar seeks no longer valid ranges.

Do you know if there is a way to map a byte index back to the compressed gzip stream? Or maybe fuse together gzip and tar decompression so it only calls seek once?

**Comment by jeffallen** [comment]
The gzip file format is not capable of seeking. See [this SO question](https://stackoverflow.com/questions/75816824/implement-seek-in-read-only-gzip-stream) for a discussion of a workaround strategy.

I will not be able to implement anything like this in this repo, but you are free to fork it and experiment.
